package Help;

public enum HeroId {
    h1("Antimage"),
    h2("Axe"),
    h3("Bane"),
    h4("Bloodseeker"),
    h5("Crystal Maiden"),
    h6("Drow Ranger"),
    h7("Earthshaker"),
    h8("Juggernaut"),
    h9("Mirana"),
    h10("Morphling"),
    h11("Shadow Fiend"),
    h12("Phantom Lancer"),
    h13("Puck"),
    h14("Pudge"),
    h15("Razor"),
    h16("Sandking"),
    h17("Storm Spirit"),
    h18("Sven"),
    h19("Tiny"),
    h20("Vengeful Spirit"),
    h21("Windranger"),
    h22("Zeus"),
    h23("Kunkka"),
    h25("Lina"),
    h26("Lion"),
    h27("Lich"),
    h28("Shadow Shaman"),
    h29("Slardar"),
    h30("Tidehunter"),
    h31("Witch Doctor"),
    h32("Riki"),
    h33("Enigma"),
    h34("Tinker"),
    h35("Sniper"),
    h36("Necrophos"),
    h37("Warlock"),
    h38("Beastmaster"),
    h39("Queen of Pain"),
    h40("Venomancer"),
    h41("Faceless Void"),
    h42("Wraith King"),
    h43("Death Prophet"),
    h44("Phantom Assassin"),
    h45("Pugna"),
    h46("Templar Assassin"),
    h47("Viper"),
    h48("Luna"),
    h49("Dragon Knight"),
    h50("Dazzle"),
    h51("Clockwerk"),
    h52("Leshrac"),
    h53("Nature's Prophet"),
    h54("Lifestealer"),
    h55("Dark Seer"),
    h56("Clinkz"),
    h57("Omniknight"),
    h58("Enchantress"),
    h59("Huskar"),
    h60("Night Stalker"),
    h61("Broodmother"),
    h62("Bounty Hunter"),
    h63("Weaver"),
    h64("Jakiro"),
    h65("Batrider"),
    h66("Chen"),
    h67("Spectre"),
    h68("Ancient Apparition"),
    h69("Doom"),
    h70("Ursa"),
    h71("Spirit Breaker"),
    h72("Gyrocopter"),
    h73("Alchemist"),
    h74("Invoker"),
    h75("Silencer"),
    h76("Outworld Devourer"),
    h77("Lycan"),
    h78("Brewmaster"),
    h79("Shadow Demon"),
    h80("Lone Druid"),
    h81("Chaos Knight"),
    h82("Meepo"),
    h83("Treant Protector"),
    h84("Ogre Magi"),
    h85("Undying"),
    h86("Rubick"),
    h87("Disruptor"),
    h88("Nyx Assassin"),
    h89("Naga Siren"),
    h90("Keeper of the Light"),
    h91("io"),
    h92("Visage"),
    h93("Slark"),
    h94("Medusa"),
    h95("Troll Warlord"),
    h96("Centaur Warrunner"),
    h97("Magnus"),
    h98("Timbersaw"),
    h99("Bristleback"),
    h100("Tusk"),
    h101("Skywrath Mage"),
    h102("Abaddon"),
    h103("Elder"),
    h104("Legion Commander"),
    h106("Ember"),
    h107("Earth Spirit"),
    h108("Underlord"),
    h109("Terrorblade"),
    h110("Phoenix"),
    h105("Techies"),
    h111("Oracle"),
    h112("Winter Wyvern"),
    h113("Arc Warden"),
    h114("Monkey King"),
    h119("Dark Willow"),
    h120("Pangolier"),
    h121("Grimstroke"),
    h129("Mars");


    private String hero;

    HeroId(String hero) {
        this.hero = hero;
    }

    @Override
    public String toString() {
        return this.hero;
    }

}
