package Help;

public enum HeroId {
    h1("anti"),
    h2("axe"),
    h3("bane"),
    h4("blood"),
    h5("crystal"),
    h6("drow"),
    h7("earthshaker"),
    h8("juggernaut"),
    h9("mirana"),
    h10("shadow-fiend"),
    h11("morphling"),
    h12("phantom-lancer"),
    h13("puck"),
    h14("pudge"),
    h15("razor"),
    h17("sand"),
    h18("storm"),
    h19("sven"),
    h20("tiny"),
    h21("vengeful"),
    h22("windrunner"),
    h23("kunkka"),
    h25("lina"),
    h26("lich"),
    h27("lion"),
    h28("shadow-shaman"),
    h29("slardar"),
    h30("tidehunter"),
    h31("witch"),
    h32("riki"),
    h33("enigma"),
    h34("tinker"),
    h35("sniper"),
    h36("necrophos"),
    h37("warlock"),
    h38("beastmaster"),
    h39("queen"),
    h40("venomancer"),
    h41("faceless"),
    h42("wraith"),
    h43("death"),
    h44("phantom_assassin"),
    h45("pugna"),
    h46("templar"),
    h47("viper"),
    h48("luna"),
    h49("dragon"),
    h50("dazzle"),
    h51("clockwerk"),
    h52("leshrac"),
    h53("natures"),
    h54("lifestealer"),
    h55("dark-seer"),
    h56("clinkz"),
    h57("omniknight"),
    h58("enchantress"),
    h59("huskar"),
    h60("night"),
    h61("broodmother"),
    h62("bounty"),
    h63("weaver"),
    h64("jakiro"),
    h65("batrider"),
    h66("chen"),
    h67("spectre"),
    h68("doom"),
    h69("ancient"),
    h70("ursa"),
    h71("spirit"),
    h72("gyrocopter"),
    h73("alchemist"),
    h74("invoker"),
    h75("silencer"),
    h76("outworld"),
    h77("lycan"),
    h78("brewmaster"),
    h79("shadow_demon"),
    h80("lone"),
    h81("chaos"),
    h82("meepo"),
    h83("treant"),
    h84("ogre"),
    h85("undying"),
    h86("rubick"),
    h87("disruptor"),
    h88("nyx"),
    h89("naga"),
    h90("keeper"),
    h91("io"),
    h92("visage"),
    h93("slark"),
    h94("medusa"),
    h95("troll"),
    h96("centaur"),
    h97("magnus"),
    h98("timbersaw"),
    h99("bristleback"),
    h100("tusk"),
    h101("skywrath "),
    h102("abaddon"),
    h103("elder"),
    h104("legion"),
    h106("ember"),
    h107("earth"),
    h108("underlord"),
    h109("terrorblade"),
    h110("phoenix"),
    h105("techies"),
    h111("oracle"),
    h112("winter"),
    h113("arc"),
    h114("monkey"),
    h119("dark_willow"),
    h120("pangolier"),
    h121("grimstroke"),
    h129("mars");


    private String hero;

    HeroId(String hero) {
        this.hero = hero;
    }

    @Override
    public String toString() {
        return this.hero;
    }

}
